WebApp/Iamopen.Site/Iamopen.Site/Controllers/InstitutionController.cs
using System;
using System.Data.SqlClient;
using System.Linq;
using System.Web.Mvc;
using System.Data;
using IAmOpen.Site.Model.Abstractions;
using IAmOpen.Site.Model.Concrete.Database;
using IAmOpen.Site.Model.Models;
using Iamopen.Availability.OnlineAvailability.Implementation;
using Iamopen.Availability.OnlineAvailability.Interface.Models;

namespace Iamopen.Site.Controllers
{
    public class InstitutionController : Controller
    {
        private readonly IUnitOfWork unitOfWork;

        //
        // GET: /Institution/

        public InstitutionController(IUnitOfWork unit)
        {
            unitOfWork = unit;
        }

        public ActionResult Index()
        {
            return View(unitOfWork.InstitutionRepository.Get().ToList());
        }

        //
        // GET: /Institution/Details/5

        public ViewResult Details(int id)
        {
            Institution institution = unitOfWork.InstitutionRepository.GetByID(id);
            return View(institution);
        }

        //
        // GET: /Institution/Create

        public ActionResult Create()
        {
            ViewBag.StatusID = new SelectList(unitOfWork.StatusRepository.Get(), "ID", "Name");
            ViewBag.StateID = new SelectList(unitOfWork.StateRepository.Get(), "ID", "Name");
            ViewBag.ChainID = new SelectList(unitOfWork.ChainRepository.Get(), "ID", "Name");
            ViewBag.UserID = new SelectList(unitOfWork.UserRepository.Get(), "ID", "NickName");
            return View();
        }

        //
        // POST: /Institution/Create

        [HttpPost]
        public ActionResult Create(Institution institution)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    unitOfWork.InstitutionRepository.Insert(institution);
                    unitOfWork.Save();
                    return RedirectToAction("Index");
                }
            }
            catch (DataException)
            {
                ModelState.AddModelError("", "Unable to save changes. Try again, and if the problem persists, see your system administrator.");
            }
            FillStatuses(institution.StatusID);
            FillStates(institution.StateID);
            FillChains(institution.ChainID);
            FillUsers(institution.UserID);
            return View(institution);
        }

        //
        // GET: /Institution/Edit/5

        public ActionResult Edit(int id)
        {
            // MM: example calling stored procedure

            //using (InstitutionContext context = new InstitutionContext())
            //{
            //    var c = context.Database.SqlQuery<Institution>("TestProc @InstitutionID",
            //        new SqlParameter("InstitutionID", 3));
            //    var f = c.ToList();
            //}
            
            Institution institution = unitOfWork.InstitutionRepository.GetByID(id);
            FillStatuses(institution.StatusID);
            FillStates(institution.StateID);
            FillChains(institution.ChainID);
            FillUsers(institution.UserID);
            return View(institution);
        }

        //
        // POST: /Institution/Edit/5

        [HttpPost]
        public ActionResult Edit(Institution institution)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    unitOfWork.InstitutionRepository.Update(institution);
                    unitOfWork.Save();
                    return RedirectToAction("Index");
                }
            }
            catch (DataException)
            {
                ModelState.AddModelError("", "Unable to save changes. Try again, and if the problem persists, see your system administrator.");
            }
            FillStatuses(institution.StatusID);
            FillStates(institution.StateID);
            FillChains(institution.ChainID);
            FillUsers(institution.UserID);
            return View(institution);
        }

        //
        // GET: /Institution/Delete/5

        public ActionResult Delete(int id)
        {
            Institution institution = unitOfWork.InstitutionRepository.GetByID(id);
            return View(institution);
        }

        //
        // POST: /Institution/Delete/5

        [HttpPost, ActionName("Delete")]
        public ActionResult DeleteConfirmed(int id)
        {
            Institution institution = unitOfWork.InstitutionRepository.GetByID(id);
            unitOfWork.InstitutionRepository.Delete(institution);
            unitOfWork.Save();
            return RedirectToAction("Index");
        }


        public ActionResult OnlineAvailability(int id)
        {
            InstitutionOnlineStatusRequestResult data;
            using (var reservationManager = new OnlineAvailabilityManager())
            {
                // note MM: very serious bug fixed. concerning dll Hell. 
                // When invoking context.Database.SqlQuery<>() ... from assemly IAmOpen.Common AccessViolation was thrown 
                // this was because this assembly had a reference to EntityFramework.dll , v4.0, and all others had v4.1 with support of sql queries
                // If anything similar happens - change reference of a library to a local copy (in lib folder)
                
                // now, stored procedures are safely invoked, but still with few bugs, that dont let use this funcitonality

                //var d = reservationManager.ReserveTable(new ReservationInfo()
                //                                            {
                //                                                TableID = 5,
                //                                                UserInfo = new UserInfo() { UserSID = 1 },
                //                                                ReservationTime = DateTime.Now
                //                                            });


                data = reservationManager.GetInstitutionOnlineStatus(
                       new InstitutionOnlineStatusRequestInfo
                       {
                           InstitutionID = id
                       });
            }
            return View(data);
        }


        private void FillStatuses(object selectedStatus = null)
        {
            var statuses = unitOfWork.StatusRepository.Get(
                orderBy: q => q.OrderBy(d => d.Name));
            ViewBag.StatusID = new SelectList(statuses, "ID", "Name", selectedStatus);
        }

        private void FillStates(object selectedState = null)
        {
            var states = unitOfWork.StateRepository.Get(
                orderBy: q => q.OrderBy(d => d.Name));
            ViewBag.StateID = new SelectList(states, "ID", "Name", selectedState);
        }

        private void FillChains(object selectedChain = null)
        {
            var chains = unitOfWork.ChainRepository.Get(
                orderBy: q => q.OrderBy(d => d.Name));
            ViewBag.ChainID = new SelectList(chains, "ID", "Name", selectedChain);
        }

        private void FillUsers(object selectedUser = null)
        {
            var users = unitOfWork.UserRepository.Get(
                orderBy: q => q.OrderBy(d => d.Nickname));
            ViewBag.ChainID = new SelectList(users, "ID", "Nickname", selectedUser);
        }
    }
}

WebApp/Iamopen.Site/Iamopen.Site/Views/Institution/Create.cshtml
@model IAmOpen.Site.Model.Models.Institution

@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>

<script src="@Url.Content("~/Scripts/lib/jquery.validate.min.js")" type="text/javascript"></script>
<script src="@Url.Content("~/Scripts/lib/jquery.validate.unobtrusive.min.js")" type="text/javascript"></script>

@using (Html.BeginForm()) {
    @Html.ValidationSummary(true)
    <fieldset>
        <legend>Institution</legend>

        <div class="editor-label">
            @Html.LabelFor(model => model.IconPath)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.IconPath)
            @Html.ValidationMessageFor(model => model.IconPath)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.CreatedDLC)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.CreatedDLC)
            @Html.ValidationMessageFor(model => model.CreatedDLC)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.CoordinatesX)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.CoordinatesX)
            @Html.ValidationMessageFor(model => model.CoordinatesX)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.CoordinatesY)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.CoordinatesY)
            @Html.ValidationMessageFor(model => model.CoordinatesY)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.UserID)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.UserID)
            @Html.ValidationMessageFor(model => model.UserID)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.StatusID, "Status")
        </div>
        <div class="editor-field">
            @Html.DropDownList("StatusID",  String.Empty)
            @Html.ValidationMessageFor(model => model.StatusID)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.StateID, "State")
        </div>
        <div class="editor-field">
            @Html.DropDownList("StateID", String.Empty)
            @Html.ValidationMessageFor(model => model.StateID)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.Rating)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.Rating)
            @Html.ValidationMessageFor(model => model.Rating)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.ChainID, "Chain")
        </div>
        <div class="editor-field">
            @Html.DropDownList("ChainID", String.Empty)
            @Html.ValidationMessageFor(model => model.ChainID)
        </div>

        <p>
            <input type="submit" value="Create" />
        </p>
    </fieldset>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

WebApp/Iamopen.Site/Iamopen.Site/Views/Institution/Delete.cshtml
@model IAmOpen.Site.Model.Models.Institution

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<fieldset>
    <legend>Institution</legend>

    <div class="display-label">IconPath</div>
    <div class="display-field">
        @Html.DisplayFor(model => model.IconPath)
    </div>

    <div class="display-label">CreatedDLC</div>
    <div class="display-field">
        @Html.DisplayFor(model => model.CreatedDLC)
    </div>

    <div class="display-label">CoordinatesX</div>
    <div class="display-field">
        @Html.DisplayFor(model => model.CoordinatesX)
    </div>

    <div class="display-label">CoordinatesY</div>
    <div class="display-field">
        @Html.DisplayFor(model => model.CoordinatesY)
    </div>

    <div class="display-label">UserID</div>
    <div class="display-field">
        @Html.DisplayFor(model => model.UserID)
    </div>

    <div class="display-label">Status</div>
    <div class="display-field">
        @Html.DisplayFor(model => model.Status.Name)
    </div>

    <div class="display-label">State</div>
    <div class="display-field">
        @Html.DisplayFor(model => model.State.Name)
    </div>

    <div class="display-label">Rating</div>
    <div class="display-field">
        @Html.DisplayFor(model => model.Rating)
    </div>

    <div class="display-label">Chain</div>
    <div class="display-field">
        @Html.DisplayFor(model => model.Chain.Name)
    </div>
</fieldset>
@using (Html.BeginForm()) {
    <p>
        <input type="submit" value="Delete" /> |
        @Html.ActionLink("Back to List", "Index")
    </p>
}

WebApp/Iamopen.Site/Iamopen.Site/Views/Institution/Details.cshtml
@model IAmOpen.Site.Model.Models.Institution

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<fieldset>
    <legend>Institution</legend>

    <div class="display-label">IconPath</div>
    <div class="display-field">
        @Html.DisplayFor(model => model.IconPath)
    </div>

    <div class="display-label">CreatedDLC</div>
    <div class="display-field">
        @Html.DisplayFor(model => model.CreatedDLC)
    </div>

    <div class="display-label">CoordinatesX</div>
    <div class="display-field">
        @Html.DisplayFor(model => model.CoordinatesX)
    </div>

    <div class="display-label">CoordinatesY</div>
    <div class="display-field">
        @Html.DisplayFor(model => model.CoordinatesY)
    </div>

    <div class="display-label">UserID</div>
    <div class="display-field">
        @Html.DisplayFor(model => model.UserID)
    </div>

    <div class="display-label">Status</div>
    <div class="display-field">
        @Html.DisplayFor(model => model.Status.Name)
    </div>

    <div class="display-label">State</div>
    <div class="display-field">
        @Html.DisplayFor(model => model.State.Name)
    </div>

    <div class="display-label">Rating</div>
    <div class="display-field">
        @Html.DisplayFor(model => model.Rating)
    </div>

    <div class="display-label">Chain</div>
    <div class="display-field">
        @Html.DisplayFor(model => model.Chain.Name)
    </div>
</fieldset>
<p>
    @Html.ActionLink("Edit", "Edit", new { id=Model.ID }) |
    @Html.ActionLink("Back to List", "Index")
</p>

WebApp/Iamopen.Site/Iamopen.Site/Views/Institution/Edit.cshtml
@model IAmOpen.Site.Model.Models.Institution

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>

<script src="@Url.Content("~/Scripts/lib/jquery.validate.min.js")" type="text/javascript"></script>
<script src="@Url.Content("~/Scripts/lib/jquery.validate.unobtrusive.min.js")" type="text/javascript"></script>

@using (Html.BeginForm()) {
    @Html.ValidationSummary(true)
    <fieldset>
        <legend>Institution</legend>

        <div class="editor-label">
            @Html.LabelFor(model => model.IconPath)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.IconPath)
            @Html.ValidationMessageFor(model => model.IconPath)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.CreatedDLC)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.CreatedDLC)
            @Html.ValidationMessageFor(model => model.CreatedDLC)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.CoordinatesX)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.CoordinatesX)
            @Html.ValidationMessageFor(model => model.CoordinatesX)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.CoordinatesY)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.CoordinatesY)
            @Html.ValidationMessageFor(model => model.CoordinatesY)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.UserID)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.UserID)
            @Html.ValidationMessageFor(model => model.UserID)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.StatusID, "Status")
        </div>
        <div class="editor-field">
            @Html.DropDownList("StatusID", String.Empty)
            @Html.ValidationMessageFor(model => model.StatusID)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.StateID, "State")
        </div>
        <div class="editor-field">
            @Html.DropDownList("StateID", String.Empty)
            @Html.ValidationMessageFor(model => model.StateID)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.Rating)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.Rating)
            @Html.ValidationMessageFor(model => model.Rating)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.ChainID, "Chain")
        </div>
        <div class="editor-field">
            @Html.DropDownList("ChainID", String.Empty)
            @Html.ValidationMessageFor(model => model.ChainID)
        </div>

        @Html.HiddenFor(model => model.ID)

        <p>
            <input type="submit" value="Save" />
        </p>
    </fieldset>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

WebApp/Iamopen.Site/Iamopen.Site/Views/Institution/Index.cshtml
@model IEnumerable<IAmOpen.Site.Model.Models.Institution>

@{
    ViewBag.Title = "Index";
}

<h2>Index</h2>

<p>
    @Html.ActionLink("Create New", "Create")
</p>
<table>
    <tr>
        <th>
            IconPath
        </th>
        <th>
            CreatedDLC
        </th>
        <th>
            CoordinatesX
        </th>
        <th>
            CoordinatesY
        </th>
        <th>
            UserID
        </th>
        <th>
            Status
        </th>
        <th>
            State
        </th>
        <th>
            Rating
        </th>
        <th>
            Chain
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.IconPath)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.CreatedDLC)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.CoordinatesX)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.CoordinatesY)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.UserID)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Status.Name)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.State.Name)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Rating)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Chain.Name)
        </td>
        <td>
            @Html.ActionLink("Edit", "Edit", new { id=item.ID }) |
            @Html.ActionLink("Details", "Details", new { id=item.ID }) |
            @Html.ActionLink("Delete", "Delete", new { id=item.ID })
        </td>
    </tr>
}

</table>

WebApp/Iamopen.Site/Iamopen.Site/Views/Institution/OnlineAvailability.cshtml
@using Iamopen.Availability.OnlineAvailability.Interface.Models
@model InstitutionOnlineStatusRequestResult
@{
   ViewBag.Title = "title";
}
<h2>
   title</h2>
<style>
   .hall-info {
      background-color: darkgrey;
      margin: 5px;
   }
   .hall-info p {
      padding-left: 20px;
   }
   
</style>
@{
   foreach (var hall in Model.Halls)
   {
      
   <div class="hall-info">
      Hall info: 
      ID=@hall.HallID
      Name= @hall.Name
      @foreach (var table in hall.Tables)
      {
         <p>
            Table Info: ID= @table.TableID
            No= @table.TableNo
            Status= @table.TableStatus.ToString()</p>
      }
   </div>
   
   }
}

WebApp/Iamopen.Site/Iamopen.Site/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
   <meta charset="utf-8" />
   <title>@ViewBag.Title</title>
   <link href="@Url.Content("~/Content/Site.css")" rel="stylesheet" type="text/css" />
</head>
<body>
   <h1>
      Last page reload time: @DateTime.Now.ToString()
   </h1>
   <div class="main-wrapper">
      @RenderBody()
   </div>
   <script src="@Url.Content("~/Scripts/lib/jmvc/jquery-1.6.4.min.js")" ></script>
   <script src="@Url.Content("~/Scripts/lib/jmvc/jquerymx-3.2.custom.min.js")" ></script>
   <script>
      window.iamopen = {
         meta: {
            mainWrapperClass: "main-wrapper",
            useAjax: true,
            links: {
               createInstitution: '@Url.Action("Create", "Institution")',
               deleteInstitution: '@Url.Action("Delete", "Institution")',
               editInstitution: '@Url.Action("Edit", "Institution")',
               showInstitutions: '@Url.Action("Index", "Institution")',
               institutionDetails: '@Url.Action("Details", "Institution")'
            }
         }
      }
   </script>
   <script src="@Url.Content("~/Scripts/iamopen/iamopen.helpers.js")"></script>
   <script src="@Url.Content("~/Scripts/iamopen/actions/iamopen.Action.js")"></script>
   <script src="@Url.Content("~/Scripts/iamopen/actions/iamopen.GetAction.js")"></script>
   <script src="@Url.Content("~/Scripts/iamopen/controllers/iamopen.ControllerBase.js")"></script>
   <script src="@Url.Content("~/Scripts/iamopen/controllers/iamopen.GetController.js")"></script>
   <script src="@Url.Content("~/Scripts/iamopen/iamopen.setup.js")"></script>
</body>
</html>